version: "3"

services:
  app:
    env_file: 
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs.express
    volumes: 
      - ".:/usr/src/app"
    ports:
      - "3001:3000"